name: v9web_presubmits

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    continue-on-error: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: node install
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: java install
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: get node version
        id: get-node-version
        shell: bash
        run: echo "::set-output name=version::$(node --version)"

      - name: cache node dependencies
        uses: actions/cache@v3
        with:
          path: v9web/node_modules
          key: ${{ runner.os }}-${{ steps.get-node-version.outputs.version }}-${{ hashFiles('v9web/yarn.lock') }}

      - name: cache firestore emulator
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/firebase/emulators
          key: ${{ runner.os }}-${{ hashFiles('v9web/yarn.lock') }}

      - name: install dependencies
        shell: bash
        run: |
          set -euo pipefail
          exec 2>&1
          set -xv

          node --version
          java -version

          npm install -g yarn
          yarn --version

          cd v9web
          yarn install --frozen-lockfile

          $(yarn bin firebase) --version

      - name: compile all files with tsc
        shell: bash
        run: cd v9web && yarn tsc

      - name: build browser bundle with rollup
        shell: bash
        run: cd v9web && yarn build

      - name: test with node
        shell: bash
        timeout-minutes: 1
        run: cd v9web && yarn run:emulator

      - name: check code formatting
        shell: bash
        run: cd v9web && yarn prettier:check
